# Start with a base image containing Java runtime
FROM openjdk:11

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Add the application's jar to the container
ADD target/chat-bot-1.0-SNAPSHOT.jar

# Run the jar file
ENTRYPOINT ["java","-jar","/chat-bot.jar"]

